### ISSUE TITLE
[BUG] saving images issue 

### ISSUE THREAD

**Issue by Rogal80** [s9roll7/face_crop_img2img#1]
Hi, awesome extension, but unfortunately I have always issue like this :

Traceback (most recent call last):
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\face_crop_img2img\scripts\face_crop_img2img.py", line 237, in run
    bg = merge_face(bg, face_img, coord, base_img_size, mask)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\face_crop_img2img\scripts\face_crop_img2img.py", line 167, in merge_face
    img_array[y: y+h, x: x+w] = mask * face_array + (1-mask)*bg
ValueError: operands could not be broadcast together with shapes (101,89,3) (101,89,4)

Any chance to fix ?

**Comment by s9roll7** [comment]
Thank you for the report.
I think it's fixed in the latest version.

**Comment by Rogal80** [comment]
thx :) its working now
